/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.system.views;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import quiz.system.util.DBConnection;

/**
 *
 * @author Nandhu
 */
public class CreatingQuizzes extends javax.swing.JFrame {

    Connection conn;
    Statement st;
    ResultSet rs;
    String query, username, quizName;
    int stat, i = 0;
    
    public void setCreds(String user, String quiz){
        username = user;
        quizName = quiz;
    }
    /**
     * Creates new form CreatingQuizzes
     */
    public CreatingQuizzes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        quesTBox = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        opt2TBox = new javax.swing.JTextField();
        opt1TBox = new javax.swing.JTextField();
        opt3TBox = new javax.swing.JTextField();
        opt4TBox = new javax.swing.JTextField();
        correctTBox = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        dropButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quesTBox.setColumns(20);
        quesTBox.setRows(5);
        jScrollPane1.setViewportView(quesTBox);

        jLabel1.setText("Question");

        jLabel2.setText("Option 1");

        jLabel3.setText("Option 2");

        jLabel4.setText("Option 3");

        jLabel5.setText("Option 4");

        jLabel6.setText("Correct Option");

        opt4TBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4TBoxActionPerformed(evt);
            }
        });

        correctTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctTBoxActionPerformed(evt);
            }
        });

        saveButton.setText("Save Quiz");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        backButton.setText(" Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        dropButton.setText("Clear ");
        dropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add Question");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(418, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(correctTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opt1TBox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(opt2TBox, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opt4TBox)
                                    .addComponent(opt3TBox, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))))
                        .addGap(0, 74, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(saveButton)
                .addGap(34, 34, 34)
                .addComponent(backButton)
                .addGap(35, 35, 35)
                .addComponent(dropButton)
                .addGap(30, 30, 30)
                .addComponent(addButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(opt1TBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(opt2TBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(opt3TBox, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(opt4TBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correctTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(backButton)
                    .addComponent(dropButton)
                    .addComponent(addButton))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt4TBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4TBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4TBoxActionPerformed

    private void correctTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctTBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane success = new JOptionPane();
        JOptionPane.showMessageDialog(new JFrame(), "Your test has been added successfully! ", "Success", JOptionPane.INFORMATION_MESSAGE);
        CreatorFrame cf = new CreatorFrame();
        cf.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here: 
        i--;
        try{
            conn = DBConnection.getInstance().connectUsers();
            st = conn.createStatement();
            query = "select * from " + quizName + "_" + username + " where no = " + i;
            ResultSet rset = st.executeQuery(query);
            while(rset.next()){
                String question = rset.getString("question");
                quesTBox.setText(question);
                String opt1 = rset.getString("opt1");
                opt1TBox.setText(opt1);
                String opt2 = rset.getString("opt2");
                opt2TBox.setText(opt2);
                String opt3 = rset.getString("opt3");
                opt3TBox.setText(opt3);
                String opt4 = rset.getString("opt4");
                opt4TBox.setText(opt4);
                String correct = rset.getString("rightOpt");
                correctTBox.setText(correct);
                
                
            }
            
            conn.close();
                   
       
        } catch (SQLException | IOException | ClassNotFoundException ex) {
            Logger.getLogger(CreatingQuizzes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void dropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropButtonActionPerformed
        // TODO add your handling code here:
        quesTBox.setText("");
        opt1TBox.setText("");
        opt2TBox.setText("");
        opt3TBox.setText("");
        opt4TBox.setText("");
        correctTBox.setText("");
    }//GEN-LAST:event_dropButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String ques = quesTBox.getText();
        String opt1 = opt1TBox.getText();
        String opt2 = opt2TBox.getText();
        String opt3 = opt3TBox.getText();
        String opt4 = opt4TBox.getText();
        String corrOpt = correctTBox.getText();
        i += 1;
        try{
            conn = DBConnection.getInstance().connectUsers();
            st = conn.createStatement();
            query = "insert into " + quizName + "_" + username + " values(" + i + ", '" + ques + "', '" + opt1 + "', '" +  opt2 + "', '" + opt3 + "', '" +  opt4 + "', '" + corrOpt + "');";
            stat = st.executeUpdate(query);
            if(stat != 0){
                JOptionPane jop = new JOptionPane();
                JOptionPane.showMessageDialog(new JFrame(), "Question " + i + " added.","Successful", JOptionPane.INFORMATION_MESSAGE);
                jop.setVisible(true);
                quesTBox.setText("");
                opt1TBox.setText("");
                opt2TBox.setText("");
                opt3TBox.setText("");
                opt4TBox.setText("");
                correctTBox.setText("");
                
            }  
            else{
                i--;
                JOptionPane jop = new JOptionPane();
                JOptionPane.showMessageDialog(new JFrame(), "Unable to add question.","Error", JOptionPane.ERROR_MESSAGE);
                jop.setVisible(true);
                quesTBox.setText("");
                opt1TBox.setText("");
                opt2TBox.setText("");
                opt3TBox.setText("");
                opt4TBox.setText("");
                correctTBox.setText("");
                
            }
            
            conn.close();
        } catch (IOException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(OpenPage.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatingQuizzes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatingQuizzes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatingQuizzes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatingQuizzes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatingQuizzes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField correctTBox;
    private javax.swing.JButton dropButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField opt1TBox;
    private javax.swing.JTextField opt2TBox;
    private javax.swing.JTextField opt3TBox;
    private javax.swing.JTextField opt4TBox;
    private javax.swing.JTextArea quesTBox;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
