/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.system.views;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.runtime.regexp.RegExpFactory.validate;
import quiz.system.util.DBConnection;
import quiz.system.views.QuizSelection;
import quiz.system.views.CreatorFrame;

/**
 *
 * @author Nandhu
 */
public class OpenPage extends javax.swing.JFrame {

    /**
     * Creates new form OpenPage
     */
    public OpenPage() {
        initComponents();
    }

    Connection conn;
    String uValue = "";
    String pValue = "";
    Boolean taker = false;
    Boolean admin = false;
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        unameTBox = new javax.swing.JTextField();
        pwordTBox = new javax.swing.JPasswordField();
        unameLabel = new javax.swing.JLabel();
        pwordLabel = new javax.swing.JLabel();
        userSelectLabel = new javax.swing.JLabel();
        tTakerRButton = new javax.swing.JRadioButton();
        tCreatorRButton = new javax.swing.JRadioButton();
        loginButton = new javax.swing.JButton();
        regLoginButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 300));

        unameTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTBoxActionPerformed(evt);
            }
        });

        pwordTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordTBoxActionPerformed(evt);
            }
        });

        unameLabel.setText("Enter Username");

        pwordLabel.setText("Enter Password");

        userSelectLabel.setText("I am a ");

        buttonGroup1.add(tTakerRButton);
        tTakerRButton.setText("Test Taker");
        tTakerRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTakerRButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(tCreatorRButton);
        tCreatorRButton.setText("Test Creator");
        tCreatorRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCreatorRButtonActionPerformed(evt);
            }
        });

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        regLoginButton.setText("New User?");
        regLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTakerRButton)
                        .addGap(18, 18, 18)
                        .addComponent(tCreatorRButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unameTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwordTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(loginButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(regLoginButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(unameTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwordTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userSelectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTakerRButton)
                    .addComponent(tCreatorRButton))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(31, 31, 31)
                .addComponent(regLoginButton)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tCreatorRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCreatorRButtonActionPerformed
        // TODO add your handling code here:
        /*if(evt.getSource() == tCreatorRButton)
            return true;
        else
            return false;*/
        
    }//GEN-LAST:event_tCreatorRButtonActionPerformed

    private void unameTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameTBoxActionPerformed

    private void pwordTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordTBoxActionPerformed

    private void regLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regLoginButtonActionPerformed
        // TODO add your handling code here:  
        if(evt.getSource() == regLoginButton){
            RegisterFrame reg = new RegisterFrame();
            reg.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_regLoginButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == loginButton){
            uValue = unameTBox.getText();
            pValue = pwordTBox.getText();
            taker = buttonGroup1.getSelection().equals(tTakerRButton.getModel());
            admin = buttonGroup1.getSelection().equals(tCreatorRButton.getModel());
            
            if(taker){            
                if(validateTaker(uValue, pValue)){
                    QuizSelection goToProfile = new QuizSelection();
                    goToProfile.setVisible(true);
                    //System.out.println("Login successful!");
                    goToProfile.setUser(uValue);                                       
                    this.dispose();
                }
                else{
                    JOptionPane invalidUserPane = new JOptionPane();
                    JOptionPane.showMessageDialog(new JFrame(), "Invalid username/password","Inane error", JOptionPane.ERROR_MESSAGE);
                    invalidUserPane.setVisible(true);


                }
            }
            else if(admin){
                if(validateAdmin(uValue, pValue)){
                    CreatorFrame goToProfile = new CreatorFrame();
                    goToProfile.setVisible(true);
                    //System.out.println("Login successful!");
                    goToProfile.setUser(uValue);
                    this.dispose();
                }
                else{
                    JOptionPane invalidUserPane = new JOptionPane();
                    JOptionPane.showMessageDialog(new JFrame(), "Invalid username/password","Inane error", JOptionPane.ERROR_MESSAGE);
                    invalidUserPane.setVisible(true);


                }
            }
            else{
                JOptionPane invalidUserPane = new JOptionPane();
                JOptionPane.showMessageDialog(new JFrame(), "Please select the type of user that you are","Inane error", JOptionPane.ERROR_MESSAGE);
                invalidUserPane.setVisible(true);
                
            }
        }
        
        
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void tTakerRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTakerRButtonActionPerformed
        // TODO add your handling code here:
        /*if(evt.getSource() == tTakerRButton){
            if(validate(uValue, pValue)){
                System.out.println("Validated user!");
            }
            else{
                JOptionPane invalidUserPane = new JOptionPane();
                JOptionPane.showMessageDialog(new JFrame(), "Invalid username/password","Inane error", JOptionPane.ERROR_MESSAGE);
                invalidUserPane.setVisible(true);
            }
        }*/
        
        
       
            
        
    }//GEN-LAST:event_tTakerRButtonActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpenPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpenPage().setVisible(true);
            }
        });
        
    }
    
    
    public Boolean validateTaker(String uValue, String pValue){
        boolean valid = false;
        //String uname = unameTBox.getText();
        //String pword = pwordTBox.getText();
        if (uValue==null||uValue.equals("")||(pValue==null||pValue.equals("")))
            valid = false;
        else {
            try {
                conn = DBConnection.getInstance().connectUsers();
                Statement st = conn.createStatement();
                String query = "select * from testusers where username = '" + uValue + "' && password = '" + pValue + "'";
                ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                    /*String dbUsername = rs.getString("username");
                    String dbPassword = rs.getString("password");*/
                    valid = true;       
                }   
            } catch (IOException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(OpenPage.class.getName()).log(Level.SEVERE, null, ex);
            }  
        }
         return valid;
    }
    
    
    public Boolean validateAdmin(String uValue, String pValue){
        boolean valid = false;
        //String uname = unameTBox.getText();
        //String pword = pwordTBox.getText();
        if (uValue==null||uValue.equals("")||(pValue==null||pValue.equals("")))
            valid = false;
        else {
            try {
                conn = DBConnection.getInstance().connectUsers();
                Statement st = conn.createStatement();
                String query = "select * from testadmins where username = '" + uValue + "' && password = '" + pValue + "'";
                ResultSet rs = st.executeQuery(query);
                while(rs.next()){
                    /*String dbUsername = rs.getString("username");
                    String dbPassword = rs.getString("password");*/
                    valid = true;       
                } 
            } catch (IOException | ClassNotFoundException | SQLException ex) {
                Logger.getLogger(OpenPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }return valid;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel pwordLabel;
    private javax.swing.JPasswordField pwordTBox;
    private javax.swing.JButton regLoginButton;
    private javax.swing.JRadioButton tCreatorRButton;
    private javax.swing.JRadioButton tTakerRButton;
    private javax.swing.JLabel unameLabel;
    private javax.swing.JTextField unameTBox;
    private javax.swing.JLabel userSelectLabel;
    // End of variables declaration//GEN-END:variables

    

}
