/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.system.views;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import quiz.system.util.DBConnection;

/**
 *
 * @author Nandhu
 */
public class QuizSelection extends javax.swing.JFrame {

    Connection conn;
    Statement st, sment;
    ResultSet rs, rset;
    String tests = "", username;
    /**
     * Creates new form QuizSelection
     */
    public QuizSelection() {
        initComponents();
    }
    
    public void setUser(String uname){
        this.username = uname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        takenPrompt = new javax.swing.JLabel();
        availablePrompt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        takenTArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        testsTArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        quizNameTBox = new javax.swing.JTextField();
        takeButton = new javax.swing.JButton();
        fetchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        takenPrompt.setText("You have taken the following quizzes: ");

        availablePrompt.setText("The following quizzes are available:");

        takenTArea.setEditable(false);
        takenTArea.setBackground(new java.awt.Color(240, 240, 240));
        takenTArea.setColumns(20);
        takenTArea.setRows(5);
        jScrollPane2.setViewportView(takenTArea);

        testsTArea.setEditable(false);
        testsTArea.setBackground(new java.awt.Color(240, 240, 240));
        testsTArea.setColumns(20);
        testsTArea.setRows(5);
        jScrollPane3.setViewportView(testsTArea);

        jLabel1.setText("Enter a quiz to take");

        quizNameTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizNameTBoxActionPerformed(evt);
            }
        });

        takeButton.setText("Take Quiz");
        takeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeButtonActionPerformed(evt);
            }
        });

        fetchButton.setText("Fetch Available Quizzes");
        fetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quizNameTBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(takeButton)
                                .addGap(0, 32, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(takenPrompt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(availablePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fetchButton)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(takenPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availablePrompt)
                    .addComponent(fetchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(quizNameTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quizNameTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizNameTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quizNameTBoxActionPerformed

    private void takeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeButtonActionPerformed
        // TODO add your handling code here:
        String quizName = quizNameTBox.getText();
        JOptionPane success = new JOptionPane();
        JOptionPane.showMessageDialog(new JFrame(), "You are about to take test " + quizName, "Success", JOptionPane.INFORMATION_MESSAGE);
        QuizFrame q = new QuizFrame();
        q.setVisible(true);
        q.setCreds(username, quizName);
        this.dispose();
        try {
            q.startTest();
        } catch (IOException | SQLException ex) {
            Logger.getLogger(QuizSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
        
               
           
         
        
        
        
    }//GEN-LAST:event_takeButtonActionPerformed

    private void fetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchButtonActionPerformed
        // TODO add your handling code here:
        try{
            conn = DBConnection.getInstance().connectUsers();
            st = conn.createStatement();
            String query = "select * from testadmins";
            rs = st.executeQuery(query);
            while(rs.next()){
                String admin = rs.getString("username");
                sment = conn.createStatement();
                String sql = "select * from " + admin + "_admin";
                rset = sment.executeQuery(sql);
                while(rset.next()){
                    String test = rset.getString("testName");
                    tests.concat(test + "\n");
                }
            }
            testsTArea.setText(tests);
            conn.close();
           
        } catch (IOException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(QuizSelection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fetchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel availablePrompt;
    private javax.swing.JButton fetchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField quizNameTBox;
    private javax.swing.JButton takeButton;
    private javax.swing.JLabel takenPrompt;
    private javax.swing.JTextArea takenTArea;
    private javax.swing.JTextArea testsTArea;
    // End of variables declaration//GEN-END:variables
}
