/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.system.views;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import quiz.system.util.DBConnection;
//import quiz.system.views.Score;

/**
 *
 * @author Nandhu
 */
public class QuizFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuizFrame
     */
    
    Connection conn;
    Statement st;
    ResultSet rs;
    String username = "", quizName = "";
    int s = 0, stat, i = 0, rightOption, answer;
    Boolean opt1, opt2, opt3, opt4;
    public void setCreds(String user, String quiz){
        this.username = user;
        this.quizName= quiz;
    }
    public QuizFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        option1RButton = new javax.swing.JRadioButton();
        option2RButton = new javax.swing.JRadioButton();
        opt3RB = new javax.swing.JRadioButton();
        opt4RB = new javax.swing.JRadioButton();
        nextButton = new javax.swing.JButton();
        endQuizButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        questionTPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(option1RButton);
        option1RButton.setText("Option 1");

        buttonGroup1.add(option2RButton);
        option2RButton.setText("Option 2");

        buttonGroup1.add(opt3RB);
        opt3RB.setText("Option 3");
        opt3RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3RBActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt4RB);
        opt4RB.setText("Option 4");

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        endQuizButton.setText("End Quiz");
        endQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endQuizButtonActionPerformed(evt);
            }
        });

        questionTPane.setEditable(false);
        questionTPane.setBackground(new java.awt.Color(240, 240, 240));
        jScrollPane2.setViewportView(questionTPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opt4RB)
                    .addComponent(opt3RB)
                    .addComponent(option2RButton)
                    .addComponent(option1RButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(nextButton)
                        .addGap(68, 68, 68)
                        .addComponent(endQuizButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option1RButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(option2RButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt3RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opt4RB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(endQuizButton))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt3RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3RBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3RBActionPerformed

    private void endQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endQuizButtonActionPerformed
        try{
            // TODO add your handling code here:
            conn = DBConnection.getInstance().connectUsers();
            String query = "insert into " + username + "_user values('" + quizName + "', " + s + ");";
            st = conn.createStatement();
            stat = st.executeUpdate(query);
            if(stat >= 0){
                JOptionPane score = new JOptionPane();
                JOptionPane.showMessageDialog(new JFrame(), "Your score is " + "10/12", "Score", JOptionPane.INFORMATION_MESSAGE);
                score.setVisible(true);
                this.dispose();
            }
            
        } catch (IOException | ClassNotFoundException | SQLException ex) {
            Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_endQuizButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        try {
            buttonGroup1.clearSelection();
           
            conn = DBConnection.getInstance().connectUsers();
            st = conn.createStatement();
            String fetch = "select * from " + quizName + ";";
            rs = st.executeQuery(fetch);
            i++;
            Boolean stat = rs.absolute(i);
            if(stat){
                questionTPane.setText(rs.getString("question"));
                option1RButton.setText(rs.getString("opt1"));
                option2RButton.setText(rs.getString("opt2"));
                opt3RB.setText(rs.getString("opt3"));
                opt4RB.setText(rs.getString("opt4"));
                rightOption = rs.getInt("rightOpt");
                opt1 = buttonGroup1.getSelection().equals(option1RButton.getModel());
                opt2 = buttonGroup1.getSelection().equals(option2RButton.getModel());
                opt3 = buttonGroup1.getSelection().equals(opt3RB.getModel());
                opt4 = buttonGroup1.getSelection().equals(opt4RB.getModel());
                if(opt1)
                    answer = 1;
                else if(opt2)
                    answer = 2;
                else if(opt3)
                    answer = 3;
                else if(opt4)
                    answer = 4;
                else{
                    JOptionPane choose = new JOptionPane();
                    JOptionPane.showMessageDialog(new JFrame(), "Choose an option! ", "Insane Error", JOptionPane.ERROR_MESSAGE);
                    choose.setVisible(true);
                }

                if(answer == rightOption)
                    s++;
            }else{
                this.remove(nextButton);
            }
            
            /*questionTPane.setText(rs.getString("question"));
            questionTPane.setText(rs.getString("question"));
            questionTPane.setText(rs.getString("question"));*/
              
            
            
        } catch (ClassNotFoundException | SQLException | IOException ex) {
            Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton endQuizButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JRadioButton opt3RB;
    private javax.swing.JRadioButton opt4RB;
    private javax.swing.JRadioButton option1RButton;
    private javax.swing.JRadioButton option2RButton;
    private javax.swing.JTextPane questionTPane;
    // End of variables declaration//GEN-END:variables

    void startTest() throws IOException, SQLException, FileNotFoundException {
        try {
            conn = DBConnection.getInstance().connectUsers();
            st = conn.createStatement();
            String fetch = "select * from " + quizName + ";";
            rs = st.executeQuery(fetch);
            i++;
            Boolean status = rs.absolute(i);
            if(status){
                questionTPane.setText(rs.getString("question"));
                option1RButton.setText(rs.getString("opt1"));
                option2RButton.setText(rs.getString("opt2"));
                opt3RB.setText(rs.getString("opt3"));
                opt4RB.setText(rs.getString("opt4"));
                rightOption = rs.getInt("rightOpt");
                System.out.println("The right option is " + rightOption);
                opt1 = buttonGroup1.getSelection().equals(option1RButton.getModel());
                opt2 = buttonGroup1.getSelection().equals(option2RButton.getModel());
                opt3 = buttonGroup1.getSelection().equals(opt3RB.getModel());
                opt4 = buttonGroup1.getSelection().equals(opt4RB.getModel());
                if(opt1)
                    answer = 1;
                else if(opt2)
                    answer = 2;
                else if(opt3)
                    answer = 3;
                else if(opt4)
                    answer = 4;
                else{
                    JOptionPane choose = new JOptionPane();
                    JOptionPane.showMessageDialog(new JFrame(), "Choose an option! ", "Insane Error", JOptionPane.ERROR_MESSAGE);
                    choose.setVisible(true);
                }

                if(answer == rightOption)
                    s += 1;
            }else{
                this.remove(nextButton);
            }
            
            /*questionTPane.setText(rs.getString("question"));
            questionTPane.setText(rs.getString("question"));
            questionTPane.setText(rs.getString("question"));*/
              
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuizFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
}
