/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.system.views;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import quiz.system.util.DBConnection;
import quiz.system.views.OpenPage;
import java.sql.Timestamp;


/**
 *
 * @author Nandhu
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    String uname = "", pword = "", cpword = "", email = "", fname = "", lname = "";
    Boolean taker = false, admin = false;
    Connection conn;
    int status,stat;
    public RegisterFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fNameLabel = new javax.swing.JLabel();
        fnameTBox = new javax.swing.JTextField();
        lNameLabel = new javax.swing.JLabel();
        unameRegLabel = new javax.swing.JLabel();
        lnameTBox = new javax.swing.JTextField();
        unameRegTBox = new javax.swing.JTextField();
        pwordRegLabel = new javax.swing.JLabel();
        cpwordLabel = new javax.swing.JLabel();
        emailidLabel = new javax.swing.JLabel();
        emailidTBox = new javax.swing.JTextField();
        userTypeLabel = new javax.swing.JLabel();
        takerRegRButton = new javax.swing.JRadioButton();
        creatorRegRButton = new javax.swing.JRadioButton();
        registerButton = new javax.swing.JButton();
        pwordRegTBox = new javax.swing.JPasswordField();
        cpwordTBox = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fNameLabel.setText("First name");

        fnameTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTBoxActionPerformed(evt);
            }
        });

        lNameLabel.setText("Last name");

        unameRegLabel.setText("Username");

        lnameTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTBoxActionPerformed(evt);
            }
        });

        unameRegTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameRegTBoxActionPerformed(evt);
            }
        });

        pwordRegLabel.setText("Password");

        cpwordLabel.setText("Confirm password");

        emailidLabel.setText("Email ID");

        userTypeLabel.setText("I am a");

        buttonGroup1.add(takerRegRButton);
        takerRegRButton.setText("Test Taker");

        buttonGroup1.add(creatorRegRButton);
        creatorRegRButton.setText("Test Creator");
        creatorRegRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatorRegRButtonActionPerformed(evt);
            }
        });

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        pwordRegTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordRegTBoxActionPerformed(evt);
            }
        });

        cpwordTBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwordTBoxActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNameLabel)
                            .addComponent(unameRegLabel)
                            .addComponent(pwordRegLabel)
                            .addComponent(cpwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lnameTBox)
                            .addComponent(fnameTBox)
                            .addComponent(unameRegTBox)
                            .addComponent(emailidTBox, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(pwordRegTBox)
                            .addComponent(cpwordTBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userTypeLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(takerRegRButton)
                            .addComponent(backButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerButton)
                            .addComponent(creatorRegRButton))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNameLabel)
                            .addComponent(fnameTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNameLabel)
                            .addComponent(lnameTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unameRegLabel)
                            .addComponent(unameRegTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pwordRegLabel))
                    .addComponent(pwordRegTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpwordLabel)
                    .addComponent(cpwordTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailidLabel)
                    .addComponent(emailidTBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userTypeLabel)
                    .addComponent(takerRegRButton)
                    .addComponent(creatorRegRButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerButton)
                    .addComponent(backButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnameTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTBoxActionPerformed

    private void lnameTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTBoxActionPerformed

    private void creatorRegRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatorRegRButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creatorRegRButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == registerButton){
            fname = fnameTBox.getText();
            lname = lnameTBox.getText();
            uname = unameRegTBox.getText();
            pword = pwordRegTBox.getText();
            cpword = cpwordTBox.getText();
            email = emailidTBox.getText();
            
            taker = buttonGroup1.getSelection().equals(takerRegRButton.getModel());
            admin = buttonGroup1.getSelection().equals(creatorRegRButton.getModel());
            
            System.out.print("Taker : " + taker +  "\nAdmin : " + admin);
            
            if(taker){
                try{
                conn = DBConnection.getInstance().connectUsers();
                Statement st = conn.createStatement();
                String query = "insert into testusers values ('" + fname + "', '"+ lname + "', '"+  uname + "', '" + pword + "', '" + email + "', " + 0 + ")";
                String sql = "CREATE TABLE " + uname + "_user" +
                   "(testName varchar(50), " + 
                   " score numeric )";
                status = st.executeUpdate(query);
                stat = st.executeUpdate(sql);        
                } catch (IOException | ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane invalidUserPane = new JOptionPane();
                if(status != 0 && stat >= 0){
                    JOptionPane.showMessageDialog(new JFrame(), status + " Test Taker creds created successfully! ","Successful", JOptionPane.INFORMATION_MESSAGE);
                    OpenPage op = new OpenPage();
                    op.setVisible(true);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(new JFrame(), status + " Unable to create user ","Failed", JOptionPane.ERROR_MESSAGE);
                invalidUserPane.setVisible(true);              
                
            }
            
            else if(admin){
                try{
                conn = DBConnection.getInstance().connectUsers();
                Statement st = conn.createStatement();
                String query = "insert into testadmins values ('" + fname + "', '"+ lname + "', '"+  uname + "', '" + pword + "', '" + email + "', " + 0 + ")";
                String sql = "CREATE TABLE " + uname + "_admin" +
                   "( testName varchar(50));"; 
                
                //st.executeUpdate(sql);
                status = st.executeUpdate(query);
                stat = st.executeUpdate(sql);       
                } catch (IOException | ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane invalidUserPane = new JOptionPane();
                if(status != 0 && stat >= 0){
                    JOptionPane.showMessageDialog(new JFrame(), status + " Test Admin creds created successfully! ","Successful", JOptionPane.INFORMATION_MESSAGE);
                    OpenPage op = new OpenPage();
                    op.setVisible(true);
                    this.dispose();
                } else
                    JOptionPane.showMessageDialog(new JFrame(), status + " Unable to create user ","Failed", JOptionPane.ERROR_MESSAGE);
                             
                
                 
            } else{
                JOptionPane invalid = new JOptionPane();
                JOptionPane.showMessageDialog(new JFrame(),  " Enter proper credentials!  ","Absurd Error", JOptionPane.ERROR_MESSAGE); 
                invalid.setVisible(true);
                
            }
        
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void pwordRegTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordRegTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwordRegTBoxActionPerformed

    private void cpwordTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwordTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwordTBoxActionPerformed

    private void unameRegTBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameRegTBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameRegTBoxActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        OpenPage op = new OpenPage();
        op.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cpwordLabel;
    private javax.swing.JPasswordField cpwordTBox;
    private javax.swing.JRadioButton creatorRegRButton;
    private javax.swing.JLabel emailidLabel;
    private javax.swing.JTextField emailidTBox;
    private javax.swing.JLabel fNameLabel;
    private javax.swing.JTextField fnameTBox;
    private javax.swing.JLabel lNameLabel;
    private javax.swing.JTextField lnameTBox;
    private javax.swing.JLabel pwordRegLabel;
    private javax.swing.JPasswordField pwordRegTBox;
    private javax.swing.JButton registerButton;
    private javax.swing.JRadioButton takerRegRButton;
    private javax.swing.JLabel unameRegLabel;
    private javax.swing.JTextField unameRegTBox;
    private javax.swing.JLabel userTypeLabel;
    // End of variables declaration//GEN-END:variables
}
